config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get "signin" => 'devise/sessions#new'
    delete "signout" => 'devise/sessions#destroy'
    get "signup" => 'devise/registrations#new'
  end

  root 'welcome#index'

  resources :articles

  get 'about' => 'welcome#about'
  get 'contacts' => 'welcome#contacts'
  
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter

    def authorized?(action, subject = nil)
      user && user.admin?
    end
  
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def access_denied(exception)
        redirect_to root_path, alert: exception.message
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def new
    end

    def create
        render plain: params[:article].inspect
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<h1> Articles <h1/>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
   
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to "One Month Rails", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav">
          <li class="nav-item pull-md-left"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contacts", contacts_path, class: "nav-link" %></li>
          
          <% if user_signed_in? %>
          <li class="nav-item "><%= button_to "Sign out", signout_path, method: :delete, class: "nav-link btn btn-success" %></li>
          <% else %>
          <li class="nav-item"><%= link_to "Sign up", signup_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Sign in", signin_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

     <!-- Flash Messages -->

    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
      <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 One Month</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/welcome/about.html.erb
<h1>About Me</h1>
<p> I'm a professional developer and for fun, I also do 3D art.</p>
<p> As as developer, I'm currently good at Ruby & Rails. I am hopeful in growing in python & Django. </p>
<p> In 3D art, I currently specialise in Blender & Plan to grow into Zbrush. </p>

app/views/welcome/contacts.html.erb
<h1>My Contacts</h1>
<ul><li>mail:</li>
<li>whatsapp: </li>
<li>facebook</li>
<li>instagram</li>
<li>telegram</li>
<li>tweeter</li></ul>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
<div class="jumbotron jumbotron-home">
    <div class="container">
        <h1>Welcome to my website!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %> 
    </div>
</div>
<% else %>
<div class="jumbotron jumbotron-home">
    <div class="container">
        <h1>Welcome to my website!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %> 
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
    </div>
</div>
<% end %>